# Generated by Django 6.0.1 on 2026-01-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('vicar', models.CharField(max_length=150)),
                ('asst_vicar1', models.CharField(blank=True, max_length=150)),
                ('asst_vicar2', models.CharField(blank=True, max_length=150)),
                ('asst_vicar3', models.CharField(blank=True, max_length=150)),
                ('diocese_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church_logos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_per_member_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_member_yearly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('upgrade_rate_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('upgrade_rate_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.church')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.package')),
            ],
        ),
    ]
