# Generated by Django 6.0.1 on 2026-01-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=150)),
                ('house_name', models.CharField(max_length=150)),
                ('history', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='registry.church')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('baptismal_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=150)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField(editable=False)),
                ('mobile_no', models.CharField(max_length=15)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('expired', models.BooleanField(default=False)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('date_of_baptism', models.DateField(blank=True, null=True)),
                ('parish_of_baptism', models.CharField(blank=True, max_length=150)),
                ('educational_qualification', models.CharField(blank=True, max_length=150)),
                ('sunday_school_qualification', models.CharField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('transferred_from', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registry.church')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registry.family')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.grade')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('ward_number', models.PositiveIntegerField()),
                ('place', models.CharField(max_length=150)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='registry.church')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='registry.ward'),
        ),
    ]
