# Generated by Django 6.0.1 on 2026-02-20 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='registry.member'),
        ),
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together={('church', 'register_number')},
        ),
    ]
