# Generated by Django 6.0.1 on 2026-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_member_spouse_alter_marriage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='bride_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
