# Generated by Django 6.0.1 on 2026-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_grade_relationship_family_member_ward_family_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_family_head',
            field=models.BooleanField(default=False),
        ),
    ]
