# Generated by Django 6.0.1 on 2026-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_member_is_family_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsubscription',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='churchsubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
