# Generated by Django 6.0.1 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_marriage_bride_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='inactive_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
