# Generated by Django 6.0.1 on 2026-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_churchsubscription_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsubscription',
            name='custom_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
