# Generated by Django 6.0.1 on 2026-02-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_vilichchollukuri'),
    ]

    operations = [
        migrations.CreateModel(
            name='DheshaKuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_confession_date', models.DateField()),
                ('bride_confession_date', models.DateField()),
                ('groom_name', models.CharField(max_length=150)),
                ('groom_dob', models.DateField(blank=True, null=True)),
                ('groom_age', models.PositiveIntegerField(blank=True, null=True)),
                ('groom_house_name', models.CharField(blank=True, max_length=150)),
                ('groom_family_name', models.CharField(blank=True, max_length=150)),
                ('groom_father', models.CharField(max_length=150)),
                ('groom_mother', models.CharField(max_length=150)),
                ('groom_place', models.CharField(blank=True, max_length=200)),
                ('bride_name', models.CharField(max_length=150)),
                ('bride_dob', models.DateField(blank=True, null=True)),
                ('bride_age', models.PositiveIntegerField(blank=True, null=True)),
                ('bride_house_name', models.CharField(max_length=150)),
                ('bride_family_name', models.CharField(max_length=150)),
                ('bride_father', models.CharField(max_length=150)),
                ('bride_mother', models.CharField(max_length=150)),
                ('bride_place', models.CharField(blank=True, max_length=200)),
                ('transfer_to', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhesha_kuris', to='registry.church')),
                ('marriage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dhesha_kuri', to='registry.marriage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('church', 'marriage')},
            },
        ),
    ]
