# Generated by Django 6.0.1 on 2026-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_churchsubscription_custom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsubscription',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, help_text='Number of months purchased (e.g. 3, 5, 12)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='trial_member_limit',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Max members allowed for trial package', null=True),
        ),
    ]
