# Generated by Django 6.0.1 on 2026-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_dheshakuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='panchayath',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='baptism',
            name='priest_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
