# Generated by Django 6.0.1 on 2026-01-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_churchsubscription_duration_months_package_is_trial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('NEW', 'New Subscription'), ('RENEW', 'Renewal'), ('UPGRADE', 'Upgrade')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='registry.church')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='registry.churchsubscription')),
            ],
        ),
    ]
