# Generated by Django 6.0.1 on 2026-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
