# Generated by Django 6.0.1 on 2026-03-02 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_baptism_panchayath_baptism_priest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('died_on', models.DateField(blank=True, null=True)),
                ('funeral_on', models.DateField(blank=True, null=True)),
                ('tomb_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tomb_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tomb_idn', models.CharField(blank=True, max_length=100)),
                ('reason_of_death', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_registers', to='registry.church')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='death_record', to='registry.member')),
            ],
            options={
                'unique_together': {('church', 'reg_no')},
            },
        ),
    ]
