# Generated by Django 6.0.1 on 2026-03-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_deathregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('mail_id', models.EmailField(max_length=254)),
                ('metropolitan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TombType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='folio_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PriestChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.designation')),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_history', to='registry.priest')),
            ],
        ),
        migrations.CreateModel(
            name='TombFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomb_fees', models.DecimalField(decimal_places=6, max_digits=10)),
                ('indication', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('tomb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='registry.tombtype')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(choices=[('HEAD', 'Family Head Register'), ('BAPTISM', 'Baptism Register'), ('MARRIAGE', 'Marriage Register'), ('DEATH', 'Death Register'), ('CERTIFICATE', 'Certificate')], max_length=20)),
                ('register_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('register_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('next_register_number', models.PositiveIntegerField(default=1)),
                ('register_padding', models.PositiveIntegerField(default=4, help_text='Example: 0001')),
                ('folio_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('folio_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('next_folio_number', models.PositiveIntegerField(default=1)),
                ('folio_padding', models.PositiveIntegerField(default=4)),
                ('use_financial_year', models.BooleanField(default=False)),
                ('financial_year_format', models.CharField(default='YYYY-YY', help_text='Example: 2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_settings', to='registry.church')),
            ],
            options={
                'unique_together': {('church', 'register_type')},
            },
        ),
    ]
