# Generated by Django 6.0.1 on 2026-01-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_bill_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
