# Generated by Django 6.0.1 on 2026-03-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_designation_diocese_priest_tombtype_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tombfee',
            unique_together={('tomb_type', 'indication')},
        ),
    ]
