# Generated by Django 6.0.1 on 2026-01-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_bill_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
