# Generated by Django 6.0.1 on 2026-03-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_alter_tombfee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregister',
            name='tomb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.tombtype'),
        ),
    ]
