# Generated by Django 6.0.1 on 2026-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_church_deleted_at_church_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('NEW', 'New Subscription'), ('RENEW', 'Renewal'), ('UPGRADE', 'Upgrade')], max_length=20),
        ),
    ]
