# Generated by Django 6.0.1 on 2026-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('NEW', 'New Subscription'), ('UPGRADE', 'Upgrade'), ('EXTENSION', 'Extension'), ('RENEW', 'Renewal')], max_length=20),
        ),
    ]
