# Generated by Django 6.0.1 on 2026-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_deathregister_tomb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersetting',
            name='financial_year',
            field=models.PositiveIntegerField(blank=True, help_text='Example: 2025 for FY 2025-26', null=True),
        ),
        migrations.AddField(
            model_name='registersetting',
            name='financial_year_end_month',
            field=models.PositiveIntegerField(blank=True, help_text='End month (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='registersetting',
            name='financial_year_start_month',
            field=models.PositiveIntegerField(blank=True, help_text='Start month (1-12)', null=True),
        ),
    ]
