# Generated by Django 6.0.1 on 2026-03-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_registersetting_financial_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tombfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='designation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='registry.church'),
        ),
        migrations.AddField(
            model_name='diocese',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dioces', to='registry.church'),
        ),
        migrations.AddField(
            model_name='priest',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priests', to='registry.church'),
        ),
        migrations.AddField(
            model_name='priestchange',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priest_changes', to='registry.church'),
        ),
        migrations.AddField(
            model_name='tombfee',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tomb_fees', to='registry.church'),
        ),
        migrations.AddField(
            model_name='tombtype',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tomb_type', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tombtype',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('church', 'designation_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tombfee',
            unique_together={('church', 'tomb_type', 'indication')},
        ),
        migrations.AlterUniqueTogether(
            name='tombtype',
            unique_together={('church', 'name')},
        ),
    ]
