# Generated by Django 6.0.1 on 2026-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_churchsubscription_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsubscription',
            name='pricing_origin',
            field=models.CharField(choices=[('BASE', 'Base Purchase'), ('UPGRADE', 'Upgrade Purchase')], default='BASE', help_text='How this subscription tier was acquired', max_length=10),
        ),
    ]
