# Generated by Django 6.0.1 on 2026-03-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_alter_tombfee_unique_together_designation_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dioces', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='priest',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priests', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='priestchange',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priest_changes', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='tombfee',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomb_fees', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='tombtype',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomb_type', to='registry.church'),
        ),
    ]
