# Generated by Django 6.0.1 on 2026-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_alter_designation_church_alter_diocese_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='register_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='baptism',
            unique_together={('church', 'register_number')},
        ),
    ]
