# Generated by Django 6.0.1 on 2026-01-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_churchsubscription_pricing_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_image',
            field=models.ImageField(blank=True, null=True, upload_to='family_images/'),
        ),
    ]
