# Generated by Django 6.0.1 on 2026-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_alter_baptism_register_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='groom_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='groom_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='groom_family_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='marriage',
            name='groom_house_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='register_number',
            field=models.CharField(max_length=50),
        ),
    ]
