# Generated by Django 6.0.1 on 2026-01-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_family_family_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_capacity', models.PositiveIntegerField(blank=True, help_text='Only for custom or higher member request', null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='registry.church')),
                ('current_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.package')),
                ('requested_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.package')),
            ],
        ),
    ]
