# Generated by Django 6.0.1 on 2026-02-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_upgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
