# Generated by Django 6.0.1 on 2026-03-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_marriage_groom_address_marriage_groom_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregister',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
