# Generated by Django 6.0.1 on 2026-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_alter_deathregister_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='bride_father',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='bride_mother',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='groom_father',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='groom_mother',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
