# Generated by Django 6.0.1 on 2026-02-06 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_bill_bill_number_bill_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptism_category', models.CharField(choices=[('PARISH', 'Parish (Church Member)'), ('OTHER', 'Other (Outsider)')], max_length=10)),
                ('date_of_baptism', models.DateField()),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('place_of_birth', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('baptismal_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('parish_of_baptism', models.CharField(max_length=150)),
                ('god_father', models.CharField(max_length=150)),
                ('god_mother', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptisms', to='registry.church')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.family')),
                ('main_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.member')),
                ('relation_with_main_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.relationship')),
            ],
        ),
    ]
