# Generated by Django 6.0.1 on 2026-02-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_baptism'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baptism', to='registry.member'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='main_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_main_member_in_baptisms', to='registry.member'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='relation_with_main_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baptism_record', to='registry.relationship'),
        ),
    ]
