# Generated by Django 6.0.1 on 2026-03-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_alter_marriage_bride_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombfee',
            name='tomb_fees',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
