# Generated by Django 6.0.1 on 2026-02-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_baptism_member_alter_baptism_main_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.relationship'),
        ),
    ]
