# Generated by Django 6.0.1 on 2026-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_alter_tombfee_tomb_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregister',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
