# Generated by Django 6.0.1 on 2026-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='house_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
