# Generated by Django 6.0.1 on 2026-01-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('registry', '0002_grade_relationship_family_member_ward_family_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='registry.member'),
        ),
    ]
