# Generated by Django 6.0.1 on 2026-02-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
        ('registry', '0022_alter_family_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='registry.church'),
        ),
    ]
